version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.eth_webhook
    container_name: eth_deposit_tracker
    environment:
      # - DATABASE_URL=postgresql://postgres:postgres@db:5432/eth_deposits
      - DATABASE_URL=postgresql://lakshyabhati24:0oPaImQNi2rX@ep-crimson-firefly-70756794-pooler.ap-southeast-1.aws.neon.tech/logix-login?sslmode=require
      - ALCHEMY_API_KEY=jCDsAl8JhBC4dmHzidPbiVRUioW5GcBa
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: eth_deposit_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eth_deposits
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    external: false
